/**
 * @file pwm_input_tps.h
 *
 * Throttle position read from an RC-servo-style PWM signal, e.g. the throttle servo command
 * generated by an autopilot and tapped into a digital input. The pulse width is mapped linearly
 * from pwmInputTpsMinUs (0%) to pwmInputTpsMaxUs (100%); min > max reverses the direction.
 * The sensor replaces the analog TPS1 and times out when pulses stop.
 */

#pragma once

#include "stored_value_sensor.h"

// Servo pulses outside this window are not a valid servo command
#define PWM_INPUT_TPS_PLAUSIBLE_MIN_US 500
#define PWM_INPUT_TPS_PLAUSIBLE_MAX_US 2500
// Five frames at the slowest common servo frame rate (50 Hz)
#define PWM_INPUT_TPS_TIMEOUT_MS 100

class PwmInputTps : public StoredValueSensor {
public:
	PwmInputTps() : StoredValueSensor(SensorType::Tps1, MS2NT(PWM_INPUT_TPS_TIMEOUT_MS)) { }

	// Called on both edges; isHigh is the pin level after the edge
	void onEdge(efitick_t nowNt, bool isHigh);

	// Deliberately not exposed through getRaw()/hasRaw(): callers of those expect volts
	// (check engine light range checks, TPS "grab closed/open" calibration).
	float getPulseWidthUs() const {
		return m_lastPulseWidthUs;
	}

	void showInfo(const char* sensorName) const override;

	// Forget the stored value and any pending rising edge
	void reset() {
		invalidate();
		m_hasRisingEdge = false;
		m_lastPulseWidthUs = 0;
	}

	// Pure conversion: pulse width to throttle percent, or an error code
	static SensorResult convert(float pulseWidthUs, float minUs, float maxUs);

private:
	efitick_t m_risingEdgeNt = 0;
	bool m_hasRisingEdge = false;
	float m_lastPulseWidthUs = 0;
};

bool isPwmInputTps1();
void initPwmInputTps();
void deinitPwmInputTps();

#if EFI_UNIT_TEST
PwmInputTps& getPwmInputTpsForUnitTest();
#endif // EFI_UNIT_TEST
